### ISSUE TITLE
出现错误？

### ISSUE THREAD

**Issue by zhou-tian-xing** [madderscientist/noteDigger#4]
![image](https://github.com/user-attachments/assets/1077a820-df69-4506-8255-9ee45a918aa6)
如图，我不知道是什么原因导致了错误，还是我操作的问题？总之我正常导入音频，然后出现了文件错误，提示IndexSizeError: Failed to execute 'getChannelData' on 'AudioBuffer': channel index (1) exceeds number of channels (1)

**Comment by madderscientist** [comment]
谢谢反馈，这是一个bug，已经修复。
出问题的原因是，你的音频是单声道，但是我取用了第二个声道的数据。此外我发现我没有将string转为int，所以永远进入了switch的default分支，即永远是双声道分析。现在增加了对通道数的判断。
再次感谢你的反馈！

**Comment by zhou-tian-xing** [comment]
好的，感谢您修复此bug，您的效率真令人羡慕。这是我见过最好用的扒谱工具！
